import Header from "@/components/header/Header";
import './globals.css';

export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className="main">
        <Header />
        {children}
        </body>
    </html>
  )
}
