import Link from "next/link"

export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <div>
          <Link href="/dashboard">Dashboard</Link>&nbsp;
          <Link href="/about">About</Link>&nbsp;
          <Link href="/products#sample">Products</Link>&nbsp;
        </div>
        {children}
        </body>
    </html>
  )
}
